### ISSUE TITLE
Dialog组件设置buttonNoClose:[true,true]无效

### ISSUE THREAD

**Issue by tonyyls** [MarkingCode/EasyHelper#1]
作者您好，组件非常棒，尝试在使用Dialog的时候发现个问题：

Dialog组件设置buttonNoClose:[true,true]无效。

烦请看看

**Comment by MarkingCode** [comment]
您好，非常感谢您的反馈！
1. 经测试 `buttonNoClose: [ true,true ]` 是可以正常使用的；
2. 此属性不能用于 `dialogInfo` ， `dialogSuccess`， `dialogWarn`， `dialogError` 四个组件上；
3. 此属性是 v1.2.6 版本中新增的属性，不适用于之前的版本，请您再次确认。

正常使用示例如下：
```html
<button type="button">打开对话框</button>

<script>
    $( "button" ).on("click", function () {
        Helper.ui.dialog({
            title: "对话框标题",
            content: "对话框内容",
            buttonNoClose: [ true, true ]
        });
    })
</script>
```

如您尚有疑问，可随时进行反馈，谢谢！

**Comment by MarkingCode** [comment]
您好，非常感谢您的反馈！
1. 经测试 `buttonNoClose: [ true,true ]` 是可以正常使用的；
2. 此属性不能用于 `dialogInfo` ， `dialogSuccess`， `dialogWarn`， `dialogError` 四个组件上；
3. 此属性是 v1.2.6 版本中新增的属性，不适用于之前的版本，请您再次确认。

正常使用示例如下：
```html
<button type="button">打开对话框</button>

<script>
    $( "button" ).on("click", function () {
        Helper.ui.dialog({
            title: "对话框标题",
            content: "对话框内容",
            buttonNoClose: [ true, true ]
        });
    })
</script>
```

如您尚有疑问，可随时进行反馈，谢谢！

**Comment by tonyyls** [comment]
查了下这边用的还是 v1.1.1 我搞错版本了，抱歉

**Comment by MarkingCode** [comment]
没关系的，感谢并欢迎您随时反馈！
